language: java
os: linux
dist: trusty
jdk:
  - oraclejdk11
git:
  depth: false
addons:
  sonarcloud:
    organization: "shiocms"
    token: ${SONAR_TOKEN}
script:
  - ./gradlew check
  -  sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
