apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shio-nginx-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shio-nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: shio-nginx
    spec:
      containers:
      - image: nginx:1.13
        name: shio-nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: shio-nginx-claim0
      restartPolicy: Always
      volumes:
      - name: shio-nginx-claim0
        persistentVolumeClaim:
          claimName: shio-nginx-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: shio-nginx
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: shio-nginx
  type: LoadBalancer  
status:
  loadBalancer: {}
