apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shio-mariadb-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shio-mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: shio-mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: shio
        - name: MYSQL_PASSWORD
          value: shio
        - name: MYSQL_ROOT_PASSWORD
          value: shio
        - name: MYSQL_USER
          value: shio
        image: viglet/shio-mariadb
        name: shio-mariadb
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: shio-mariadb-claim0
      restartPolicy: Always
      volumes:
      - name: shio-mariadb-claim0
        persistentVolumeClaim:
          claimName: shio-mariadb-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: shio-mariadb
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: shio-mariadb
status:
  loadBalancer: {}
