apiVersion: v1
kind: PersistentVolume
metadata:
  name: shio-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: shio-claim0 
  hostPath:
    path: "/tmp/data"
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shio-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: shio
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.mariadb.jdbc.Driver
        - name: SPRING_DATASOURCE_PASSWORD
          value: shio
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mariadb://shio-mariadb:3306/shio
        - name: SPRING_DATASOURCE_USERNAME
          value: shio
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://shio-mongodb:27017/shio
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.MySQL5InnoDBDialect
        image: viglet/shio
        name: shio
        ports:
        - containerPort: 2710
        resources: {}
        volumeMounts:
        - mountPath: /app/store
          name: shio-claim0
      restartPolicy: Always
      volumes:
      - name: shio-claim0
        persistentVolumeClaim:
          claimName: shio-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: shio
spec:
  ports:
  - name: "2710"
    port: 2710
    targetPort: 2710
  selector:
    io.kompose.service: shio
  type: LoadBalancer
status:
  loadBalancer: {}
