apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shio-mongodb-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shio-mongodb-claim1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shio-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: shio-mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_APPLICATION_DATABASE
          value: shio
        image: mongo
        name: shio-mongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: shio-mongodb-claim0
        - mountPath: /data/configdb
          name: shio-mongodb-claim1
      restartPolicy: Always
      volumes:
      - name: shio-mongodb-claim0
        persistentVolumeClaim:
          claimName: shio-mongodb-claim0
      - name: shio-mongodb-claim1
        persistentVolumeClaim:
          claimName: shio-mongodb-claim1
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: shio-mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: shio-mongodb
status:
  loadBalancer: {}
